import IMAGES from "../../common/images";

export const dummyHomeData =[
    {
        id: 0,
        image: IMAGES.test,
        name: 'Mohamed Eisa',
        location: 'Tanta,Elghrbya,Egypt',
        revew: null,
        shipping: 'two days shipping',
    },
    {
        id: 1,
        image: IMAGES.avatr,
        name: 'Ebrahim Elngary',
        location: '22 st Ali Moubarak,Tanta,Elgharbia,',
        revew: null,
        shipping: 'two days shipping',
    },
    {
        id: 2,
        image: IMAGES.test,
        name: 'Mohamed Gamal Eisa',
        location: '22 st Ali Moubarak,Tanta,Elgharbia,',
        revew: null,
        shipping: 'two days shipping',
    },
    {
        id: 3,
        image: IMAGES.avatr,
        name: 'Ebrahim Mohamed Ebrahim Elnagry',
        location: '22 st Ali Moubarak,Tanta,Elgharbia,',
        revew: null,
        shipping: 'two days shipping',
    },
    {
        id: 4,
        image: IMAGES.test,
        name: 'Mohamed Eisa',
        location: 'Tanta,Elghrbya,Egypt',
        revew: null,
        shipping: 'two days shipping',
    },
    {
        id: 5,
        image: IMAGES.avatr,
        name: 'Ebrahim Elngary',
        location: '22 st Ali Moubarak,Tanta,Elgharbia,',
        revew: null,
        shipping: 'two days shipping',
    },
    {
        id: 6,
        image: IMAGES.test,
        name: 'Mohamed Gamal Eisa',
        location: '22 st Ali Moubarak,Tanta,Elgharbia,',
        revew: null,
        shipping: 'two days shipping',
    },
    {
        id: 7,
        image: IMAGES.avatr,
        name: 'Ebrahim Mohamed Ebrahim Elnagry',
        location: '22 st Ali Moubarak,Tanta,Elgharbia,',
        revew: null,
        shipping: 'two days shipping',
    },
]