import IMAGES from '../../common/images';

export const dummyHomeData = [
  {
    id: 0,
    image: IMAGES.test,
    name: 'Mohamed Eisa',
    location: 'Tanta,Elghrbya,Egypt',
    revew: null,
    shipping: 'two days shipping',
    quantity: 40,
    review: [
      {
        id: 0,
        name: 'Ali Boskats',
        image: IMAGES.avatr,
        comment: 'this is best impoo',
        time: '10:30 PM',
      },
      {
        id: 1,
        name: 'Mido Test',
        image: IMAGES.avatr,
        comment: 'this is best impoo',
        time: '1:30 PM',
      },
      {
        id: 2,
        name: 'Amir Khan',
        image: IMAGES.avatr,
        comment: 'this is best impoo',
        time: '11:30 PM',
      },
      {
        id: 3,
        name: 'Arwa',
        image: IMAGES.avatr,
        comment: 'this is best impoo',
        time: '11:30 PM',
      },
      {
        id: 4,
        name: 'Mena',
        image: IMAGES.avatr,
        comment: 'this is best impoo',
        time: '11:30 PM',
      },
    ],
  },
  {
    id: 1,
    image: IMAGES.avatr,
    name: 'Ebrahim Elngary',
    location: '22 st Ali Moubarak,Tanta,Elgharbia,',
    revew: null,
    shipping: 'two days shipping',
    review: undefined,
    quantity: 50,
  },
  {
    id: 2,
    image: IMAGES.test,
    name: 'Mohamed Gamal Eisa',
    location: '22 st Ali Moubarak,Tanta,Elgharbia,',
    revew: null,
    shipping: 'two days shipping',
    quantity: 50,
  },
  {
    id: 3,
    image: IMAGES.avatr,
    name: 'Ebrahim Mohamed Ebrahim Elnagry',
    location: '22 st Ali Moubarak,Tanta,Elgharbia,',
    revew: null,
    shipping: 'two days shipping',
    quantity: 50,
  },
  {
    id: 4,
    image: IMAGES.test,
    name: 'Mohamed Eisa',
    location: 'Tanta,Elghrbya,Egypt',
    revew: null,
    shipping: 'two days shipping',
  },
  {
    id: 5,
    image: IMAGES.avatr,
    name: 'Ebrahim Elngary',
    location: '22 st Ali Moubarak,Tanta,Elgharbia,',
    revew: null,
    shipping: 'two days shipping',
  },
  {
    id: 6,
    image: IMAGES.test,
    name: 'Mohamed Gamal Eisa',
    location: '22 st Ali Moubarak,Tanta,Elgharbia,',
    revew: null,
    shipping: 'two days shipping',
  },
  {
    id: 7,
    image: IMAGES.avatr,
    name: 'Ebrahim Mohamed Ebrahim Elnagry',
    location: '22 st Ali Moubarak,Tanta,Elgharbia,',
    revew: null,
    shipping: 'two days shipping',
  },
];
