const ICONS = {
home: 'home',
shipped: 'shipped',
notification: 'Notification',
notificationOutline: 'notifications-outline',
order: 'orders',
account: 'user-o',
heart: 'heart',
search: 'search',
star: 'star',
location: 'location',
row:'row',
virtcal:'virtcal',
filter: 'filter',
arrowleft: 'arrow-thin-left',
arrowright: 'arrow-thin-right',
attachment: 'attachment',
cheveronDown: 'cheveron-down',
cheveronLeft: 'cheveron-left',
cheveronRight: 'cheveron-right',
cheveronUp: 'cheveron-up',
lockpassword: 'Lockpassword',
mail: 'mail',
profile: 'profile',
edit: 'edit',
bin: 'bin',
chat: 'chat',
help: 'question',
time: 'time',
eyeOn: 'eye',
eyeOff: 'eye-blocked',
telephone: 'telephone',
plus: 'plus',
radioChecked:'radio-checked',
radioUnchecked: 'radio-unchecked',
};
export default ICONS;
