const ICONS = {
  home: 'home',
  camira: 'camira',
  cart: 'cart',
  categories: 'categories',
  chat: 'chat',
  filter: 'filter',
  heart: 'heart',
  close: 'close',
  effors: 'effors',
  mail: 'mail',
  more: 'more',
  phoneRinging: 'phone-ringing',
  copy: 'sheet',
  share: 'share',
  search: 'search',
  shops: 'shops',
  sort: 'sort-az',
  unpaid: 'unpaid',
  shipped: 'shipped',
  rightArrow: 'rightArrow',
  leftArrow: 'leftArrow',
  returns: 'returns',
  processing: 'processing',
  eyeOff: 'eyeOff',
  eye: 'eye',
  creditCard: 'credit-card',
  coupon: 'coupon',
  points: 'points',
  wallet: 'wallet',
  ok: 'returns',
  whatsapp: 'whatsapp',
  google: 'google',
  facebook: 'facebook',
  instgram: 'instagram',
  empty: 'opencart',
  check: 'check',
  linkedin: 'linkedin',
  twitter: 'twitter',
  play: 'play',
  location: 'location',
  clock: 'clock',
  walletmoney: 'wallet, money',
};
export default ICONS;
